[build-system]
requires = ['setuptools==68.0.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'antitesting'
version = '0.0.5'
authors = [
  { name='Evgeniy Blinov', email='zheni-b@yandex.ru' },
]
description = 'No more testing'
readme = 'README.md'
requires-python = '>=3.7'
dependencies = [
    'typing_extensions ; python_version < "3.8"',
]
classifiers = [
    'Operating System :: OS Independent',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'License :: OSI Approved :: MIT License',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Libraries',
    'Framework :: Pytest',
]

[project.entry-points.pytest11]
antitesting = "antitesting.plugin"

[project.urls]
'Source' = 'https://github.com/pomponchik/antitesting'
'Tracker' = 'https://github.com/pomponchik/antitesting/issues'
