name: Tests

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements_dev.txt

    - name: Build the project
      shell: bash
      run: python -m build .

    - name: Upload to the pypi.org
      shell: bash
      run: twine upload dist/*
